// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8xQEBnveYGH7Ml5rPu09ETtFwwpqrez8',
    appId: '1:361600548976:web:6832bf09a3673cfe9ff4b5',
    messagingSenderId: '361600548976',
    projectId: 'global-contineo-unofficial',
    authDomain: 'global-contineo-unofficial.firebaseapp.com',
    storageBucket: 'global-contineo-unofficial.firebasestorage.app',
    measurementId: 'G-JC7GEPPRDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5MSFGLARsgGVRvNoSgKwPZYwqr2Prxao',
    appId: '1:361600548976:android:03a688938484a6999ff4b5',
    messagingSenderId: '361600548976',
    projectId: 'global-contineo-unofficial',
    storageBucket: 'global-contineo-unofficial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH-dBs3qrtgLX0kozSvjBFMXh8TQxk3AM',
    appId: '1:361600548976:ios:e074c2f38baa5e239ff4b5',
    messagingSenderId: '361600548976',
    projectId: 'global-contineo-unofficial',
    storageBucket: 'global-contineo-unofficial.firebasestorage.app',
    iosBundleId: 'com.example.globalContineoUnofficial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH-dBs3qrtgLX0kozSvjBFMXh8TQxk3AM',
    appId: '1:361600548976:ios:e074c2f38baa5e239ff4b5',
    messagingSenderId: '361600548976',
    projectId: 'global-contineo-unofficial',
    storageBucket: 'global-contineo-unofficial.firebasestorage.app',
    iosBundleId: 'com.example.globalContineoUnofficial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8xQEBnveYGH7Ml5rPu09ETtFwwpqrez8',
    appId: '1:361600548976:web:bb8f1ec49de7c9339ff4b5',
    messagingSenderId: '361600548976',
    projectId: 'global-contineo-unofficial',
    authDomain: 'global-contineo-unofficial.firebaseapp.com',
    storageBucket: 'global-contineo-unofficial.firebasestorage.app',
    measurementId: 'G-NJSJGGLDCM',
  );

}